/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import classes.Pesquisa;
import javax.swing.JOptionPane;

/**
 *
 * @author lucca
 */
public class Aplicacao extends javax.swing.JFrame {

   private Pesquisa pesquisa= new Pesquisa();
    public Aplicacao() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMICadastrar = new javax.swing.JMenu();
        jMICadastrarOpiniao = new javax.swing.JMenuItem();
        jMListar = new javax.swing.JMenu();
        jMIResultado = new javax.swing.JMenuItem();
        jMIOpcoes = new javax.swing.JMenu();
        jMISair = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Pesquisa de Opinião");

        jMICadastrar.setMnemonic('C');
        jMICadastrar.setText("Cadastrar");

        jMICadastrarOpiniao.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.CTRL_MASK));
        jMICadastrarOpiniao.setText("Opinião");
        jMICadastrarOpiniao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMICadastrarOpiniaoActionPerformed(evt);
            }
        });
        jMICadastrar.add(jMICadastrarOpiniao);

        jMenuBar1.add(jMICadastrar);

        jMListar.setText("Listar");

        jMIResultado.setText("Resultado");
        jMIResultado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMIResultadoActionPerformed(evt);
            }
        });
        jMListar.add(jMIResultado);

        jMenuBar1.add(jMListar);

        jMIOpcoes.setText("Opções");

        jMISair.setText("Sair");
        jMISair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMISairActionPerformed(evt);
            }
        });
        jMIOpcoes.add(jMISair);

        jMenuBar1.add(jMIOpcoes);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 539, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 412, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMISairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMISairActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jMISairActionPerformed

    private void jMICadastrarOpiniaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMICadastrarOpiniaoActionPerformed
        Cadastro telaCadastro = new Cadastro(this,true,pesquisa);
        telaCadastro.setLocationRelativeTo(this);
        telaCadastro.setVisible(true);
    }//GEN-LAST:event_jMICadastrarOpiniaoActionPerformed

    private void jMIResultadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMIResultadoActionPerformed
       JOptionPane.showMessageDialog(this,"Participaram da pesquisa: "+pesquisa.quantidadeEspectadoresConsultados()+"\nResultado:\n"+pesquisa.dados(),"APPpesquisadeOpinião",1);
    }//GEN-LAST:event_jMIResultadoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Aplicacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Aplicacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Aplicacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Aplicacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Aplicacao().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMICadastrar;
    private javax.swing.JMenuItem jMICadastrarOpiniao;
    private javax.swing.JMenu jMIOpcoes;
    private javax.swing.JMenuItem jMIResultado;
    private javax.swing.JMenuItem jMISair;
    private javax.swing.JMenu jMListar;
    private javax.swing.JMenuBar jMenuBar1;
    // End of variables declaration//GEN-END:variables
}
